import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Next App 2 AppAppAppApp",
    description: "Generated by Next next NextNextNextNext",
};

export default function AboutLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        
            <div>
                <ul>
                    <li>
                    <Link href={"/about/team"}>Team</Link>
                    </li>
                    <li>
                    <Link href={"/about/contact"}>Contact</Link>
                    </li>
                </ul>
                {children}
            </div>
   );
}